language: java

jdk:
  - oraclejdk8

install:
  - mvn install --settings travis-settings.xml -DskipTests=true -Dmaven.javadoc.skip=true -Dmessage="go" -DtopicName="moussatest" -Dserverurl="9.84.96.29:9092" -Dgroupid="test2" -B -V -e -U 
script:
  # Do not deploy if default script command for Maven is failing
  - mvn test --settings travis-settings.xml -Dmessage="go" -DtopicName="moussatest" -Dserverurl="9.84.96.29:9092" -Dgroupid="test2" -B && mvn deploy --settings travis-settings.xml -DskipTests=true -B 
  - |-
cache:
  directories:
  - $HOME/.m2